### ISSUE TITLE
Issue Adding customers

### ISSUE THREAD

**Issue by rg-jonathantansey** [letmeproperty/Applications#5]
Request URL: https://letme-applications.azurewebsites.net:443/api/applications/HaQVpGyKKN/customers

applicationReference: HaQVpGyKKN

customer:
    {
      "RoleType": "MasterTenant",
      "Title": "Mr",
      "GivenName": "Test",
      "AdditionalName": "Tester",
      "FamilyName": "Testington",
      "KnownAs": "Testy-McGee",
      "Gender": "Test",
      "Status": "string"
    }

**Comment by rg-kristianwilson** [comment]
Fixed in fc10cdf
