### ISSUE TITLE
Telephone Number api not returning numbers and associated data

### ISSUE THREAD

**Issue by rg-jinwood** [letmeproperty/Applications#9]
`var application =
                _applicationsContext.Applications.Active()
                    .Include(c => c.Customers.Select(t => t.TelephoneNumbers))
                    .FirstOrDefault(a => a.ApplicationReference == applicationReference);`

Missing data from the query in GetCustomerTelephoneNumbersForApplication();

**Comment by rg-kristianwilson** [comment]
Tested ok and unable to recreate.
